project2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import reminder.views as reminder_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reminder/', include('reminder.urls')),
    url(r'^login/$', auth_views.login, name = 'login'),
    url(r'^logout/$', auth_views.logout, name = 'logout'),
    url(r'^signup/$', reminder_views.signup, name='signup'),
]

reminder/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create-team/$', views.create_team, name='create_team'),
	url(r'^create-roommate/(?P<slug>[^\.]+)/$', views.create_roommate, name='create_roommate'),
	url(r'^create-chore/(?P<slug>[^\.]+)/$', views.create_chore, name='create_chore'),
	url(r'^roommate/(?P<slug>[^\.]+)/$', views.view_roommate, name='view_roommate'),
	url(r'^chore/(?P<slug>[^\.]+)/$', views.view_chore, name='view_chore'),
	url(r'^alert-later/(?P<slug>[^\.]+)/$', views.alert_later, name='alert_later'),
	url(r'^alert-now/(?P<slug>[^\.]+)/$', views.alert_now, name='alert_now'),
	url(r'^alert-recurring/(?P<slug>[^\.]+)/$', views.alert_recurring, name='alert_recurring'),
	url(r'^(?P<slug>[^\.]+)/$', views.view_team, name='view_team'),
]

reminder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
import datetime
from django.utils import timezone

class Team(models.Model):
	name = models.CharField(max_length=100)
	created = models.DateTimeField(default = timezone.now)
	#timezone (if global support necessary)
	user = models.ForeignKey(User, related_name='teams')
	slug = models.SlugField(max_length=100)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('view_team', kwargs={'slug': self.slug})

class Roommate(models.Model):
	name = models.CharField(max_length=50)
	team = models.ForeignKey('Team', related_name='roommates')
	phone_number = PhoneNumberField()
	slug = models.SlugField(max_length=100)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('view_roommate', kwargs={'slug': self.slug})

class Chore(models.Model):
	name = models.CharField(max_length=50)
	description = models.TextField()
	deadline = models.DateTimeField()
	roommate = models.ForeignKey('Roommate', related_name='chores')
	team = models.ForeignKey('Team', related_name='chores')
	slug = models.SlugField(max_length=100)
	STATUS_OPTIONS = (
		('Y', 'Complete'),
		('N', 'Incomplete'),
	)
	status = models.CharField(
		max_length = 1,
		choices = STATUS_OPTIONS,
		default = 'N',
		)

	def is_complete(self):
		self.status = 'Y'
		self.save()

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('view_chore', kwargs={'slug': self.slug})

reminder/forms.py
from django import forms
from django.utils.text import slugify
from django.forms import ModelForm

from .models import Team, Roommate, Chore

class TeamForm(ModelForm):
	class Meta:
		model = Team
		fields = ['name']

	def save(self, user):
		instance = super(TeamForm, self).save(commit=False)
		instance.slug = slugify(instance.name)
		instance.user = user
		instance.save()
		return instance

class RoommateForm(ModelForm):
	class Meta:
		model = Roommate
		fields = ['name', 'team', 'phone_number']

	def __init__(self, user, *args, **kwargs):
		super(RoommateForm, self).__init__(*args, **kwargs)
		self.fields['team'].queryset = Team.objects.filter(user=user)

	def save(self):
		instance = super(RoommateForm, self).save(commit=False)
		instance.slug = slugify(instance.name)
		instance.save()
		return instance

class ChoreForm(ModelForm):
	class Meta:
		model = Chore
		fields = ['name', 'description', 'deadline', 'roommate']
		widgets = {
			'description': forms.Textarea(attrs={'rows':5, 'cols':30}),
		}

	def __init__(self, team, *args, **kwargs):
		super(ChoreForm, self).__init__(*args, *kwargs)
		self.fields['roommate'].queryset = Roommate.objects.filter(team=team)

	def save(self, team):
		instance = super(ChoreForm, self).save(commit=False)
		instance.slug = slugify(instance.name)
		instance.team = team
		instance.save()
		return instance

class AlertLaterForm(forms.Form):
	date = forms.DateTimeField(label='When do you want to send the alert?')

class AlertRecurringForm(forms.Form):
	DAY_CHOICES = (
			('Monday', 'Monday'),
			('Tuesday', 'Tuesday'),
			('Wednesday', 'Wednesday'),
			('Thursday', 'Thursday'),
			('Friday', 'Friday'),
			('Saturday', 'Saturday'),
			('Sunday', 'Sunday'),
		)
	day = forms.ChoiceField(choices=DAY_CHOICES)
	time = forms.TimeField()

reminder/views.py
import os, sched, schedule, time, datetime, pytz
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from reminder.models import Team, Roommate, Chore
from reminder.forms import TeamForm, RoommateForm, ChoreForm, AlertLaterForm, AlertRecurringForm

from twilio.rest import Client

@login_required
def index(request):
	current_user = request.user
	teams = current_user.teams.all()
	return render(request, 'reminder/index.html', {'teams': teams})

def signup(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('index')
	else:
		form = UserCreationForm()
	return render(request, 'registration/signup.html', {'form': form})

def create_team(request):
	current_user = request.user
	if request.method == 'POST':
		form = TeamForm(request.POST)
		if form.is_valid():
			team = form.save(current_user)
			return redirect('index')
	else:
		form = TeamForm()
	return render(request, 'registration/create_team.html', {'form': form})

def create_roommate(request, slug):
	current_user = request.user
	if request.method == "POST":
		form = RoommateForm(current_user, request.POST)
		if form.is_valid():
			roommate = form.save()
			return redirect('view_team')
	else:
		form = RoommateForm(current_user)
	return render(request, 'registration/create_roommate.html', {
		'form': form,
		'team': get_object_or_404(Team, slug=slug)
		})

def create_chore(request, slug):
	team = get_object_or_404(Team, slug=slug)
	if request.method == "POST":
		form = ChoreForm(team, request.POST)
		if form.is_valid():
			chore = form.save(team)
			return redirect('view_team', slug=team.slug)
	else:
		form = ChoreForm(team)
	return render(request, 'registration/create_chore.html', {
		'form': form,
		'team': team
		})

def view_team(request, slug):
	return render(request, 'reminder/view_team.html', {
			'team': get_object_or_404(Team, slug=slug)
		})

def view_roommate(request, slug):
	return render(request, 'reminder/view_roommate.html', {
			'roommate': get_object_or_404(Roommate, slug=slug),
			'team': get_object_or_404(Roommate, slug=slug).team
		})
 
def view_chore(request, slug):
	alertlater_form = AlertLaterForm()
	alertrecurring_form = AlertRecurringForm()
	return render(request, 'reminder/view_chore.html', {
			'chore': get_object_or_404(Chore, slug=slug),
			'alertlater_form': alertlater_form,
			'alertrecurring_form': alertrecurring_form,
			'team': get_object_or_404(Chore, slug=slug).team,
			'roommate': get_object_or_404(Chore, slug=slug).roommate
		})

#Twilio Views
def alert_now(request, slug):
	#Twilio Setup
	account_sid = "AC28c62e521145b961ad432ec7f6050fce"
	auth_token = "27061d0c4ca70a43f1ffdb8e4572ae66"
	client = Client(account_sid, auth_token)

	#My Stuff
	chore = get_object_or_404(Chore, slug=slug)
	phone_num = chore.roommate.phone_number

	client.messages.create(
		to = str(phone_num),
		from_ = "+16692207006",
		body = str(' '.join([chore.name, chore.description]))
		)

	return render(request, 'reminder/view_chore.html', {
			'chore': chore
		})

def alert_later(request, slug):
	#Set up Twilio function to send text message
	def send_message(slug):
		#Twilio Setup
		account_sid = "AC28c62e521145b961ad432ec7f6050fce"
		auth_token = "27061d0c4ca70a43f1ffdb8e4572ae66"
		client = Client(account_sid, auth_token)

		chore = get_object_or_404(Chore, slug=slug)
		phone_num = chore.roommate.phone_number

		client.messages.create(
		to = str(phone_num),
		from_ = "+16692207006",
		body = str(' '.join([chore.name, chore.description]))
		)

	#Incorporates the sending date/time and uses while loop to pause function until the right time
	raw_datetime = request.POST.get('date')
	print (raw_datetime)
	datetime_format = '%m/%d/%Y %I:%M %p'
	future_datetime = datetime.datetime.strptime(raw_datetime, datetime_format)

	while datetime.datetime.now() < future_datetime:
		time.sleep(1)

	send_message(slug)
	return HttpResponse('Woot')

def alert_recurring(request, slug):
	#Set up Twilio function to send text message
	def send_message(slug):
		#Twilio Setup
		account_sid = "AC28c62e521145b961ad432ec7f6050fce"
		auth_token = "27061d0c4ca70a43f1ffdb8e4572ae66"
		client = Client(account_sid, auth_token)

		chore = get_object_or_404(Chore, slug=slug)
		phone_num = chore.roommate.phone_number

		client.messages.create(
		to = str(phone_num),
		from_ = "+16692207006",
		body = str(' '.join([chore.name, chore.description]))
		)
	#Pulling from the relevant Chore object
	chore = get_object_or_404(Chore, slug=slug)
	raw_datetime = chore.deadline

	#Converting Chore deadline to aware timezone object
	future_datetime = raw_datetime.replace(tzinfo=None)
	#Pulling from the Request object
	day = request.POST.get('day').lower()
	raw_time = str(request.POST.get('time'))
	time_ = str(datetime.datetime.strptime(raw_time, '%I:%M %p').time())[:-3]  

	def schedule_process(day, time_, slug):
		sched1 = schedule.every()
		sched2 = getattr(sched1, day)
		sched3 = sched2.at(time_).do(send_message, slug).tag(slug)
		return sched3
	job = schedule_process(day, time_, slug)

	print (datetime.datetime.now() < future_datetime )

	#Scheduling - While loop keeps function online until deadline
	while datetime.datetime.now() < future_datetime:
		schedule.run_pending()
		time.sleep(1)


	return HttpResponse('Woot')

reminder/templates/reminder/base.html
{% load static %}
<html>
	<head>
		<title>{% block head_title %}{% endblock %}</title>
		<link href="{% static 'reminder/css/main.css' %}" rel="stylesheet">
		<link href="{% static 'reminder/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'reminder/css/datetime-picker.css' %}" rel="stylesheet">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-light">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#userMenu">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="{% url 'index' %}">jarvis</a>
			<div class="collapse navbar-collapse" id="userMenu">
				<ul class="nav navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="#">Settings</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Logout</a>
					</li>
				</ul>
			</div>
		</nav>
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
		  {% if team %}
		  	<li class="breadcrumb-item"><a href="{{ team.get_absolute_url }}">{{ team.name }}</a></li>
		  {% endif %}
		  {% if form %}
		  	<li class="breadcrumb-item">Form</li>
		  {% endif %}
		  {% if roommate %}
		  	<li class="breadcrumb-item"><a href="{{ roommate.get_absolute_url }}">{{ roommate.name }}</a></li>
		  {% endif %}
		  {% if chore %}
		  	<li class="breadcrumb-item"><a href="{{ chore.get_absolute_url }}">{{ chore.name }}</a></li>
		  {% endif %}
		</ol>
		<div class="container">
			<h1 class='page-title'>{% block title %}
				{% endblock %}
			</h1>
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>
<script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
<script src="{% static 'reminder/scripts/moment.js' %}"></script>
<script src="{% static 'reminder/scripts/moment-with-locales.min.js' %}"></script>
<script src="{% static 'reminder/scripts/jquery.js' %}"></script>
<script src="{% static 'reminder/css/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'reminder/scripts/app.js' %}"></script>
<script src="{% static 'reminder/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'reminder/css/bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'reminder/css/bower_components/eonasdan-bootstrap-datetimepicker/build/js/tempusdominus-core.min.js' %}"></script>

reminder/templates/reminder/index.html
{% extends 'reminder/base.html' %}
{% block title %} Home {% endblock %}

{% block content %}
	{% if teams %}
		<div class="row team-index">
			{% for team in teams %}
				<div class='col-lg-4 card'>
					<div class='card-body'>
						<h3>{{ team.name }}</h3>
						<p>Here is the description of your team Bluxome.</p>
						<p><a class='btn btn-primary' href="{{ team.get_absolute_url }}" role='button'>View Team &raquo;</a></p>
					</div>
				</div>
			{% endfor %}
		</div>
	{% else %}
		<p>No teams registered!</p>
		<a href="{% url 'create_team' %}">Make Team</a>
	{% endif %}
{% endblock %}

reminder/templates/reminder/view_chore.html
{% extends 'reminder/base.html' %}
{% block title %} {{ chore.name }} {% endblock %}

{% block content %}
	<div class='row'>
		{% comment %}
		<div class='col-lg-12'>
			<div class='card-deck text-center'>
				<div class='card'>
					<div class="card-header" data-toggle="collapse" href="#form_alert_now"><h4 class='card-title'>Send Reminder Now</h4></div>
					<div class='card-block' id="form_alert_now">
						<p>Send a custom text alert right when you click the button</p>
						<p><a class='btn btn-primary' href="{% url 'alert_now' slug=chore.slug %}">Send Reminder Now</a></p>
					</div>
				</div>
				<div class='card'>
					<div class="card-header" data-toggle="collapse" href="#form_alert_later"><h4 class='card-title'>Send Reminder Later</h4></div>
					<div class='card-block' id="form_alert_later">
						<form id="alert_later" action="{% url 'alert_later' slug=chore.slug %}" method="POST">
							{% csrf_token %}
							<div class="form-group">
				                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
				                    <input name='date' id="id_date" type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
				                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
				                    <span class="fa fa-calendar"></span>
				                    </span>
				                </div>
				            </div>
				            <input class='btn btn-primary' type="submit" value="Submit" />
						</form>
					</div>
				</div>
				<div class='card'>
					<div class="card-header" data-toggle="collapse" href="#form_alert_recurring"><h4 class='card-title'>Schedule Recurring Reminder</h4></div>
					<div class='card-body' id="form_alert_recurring">
						<form id='alert_recurring' action="{% url 'alert_recurring' slug=chore.slug %}" method="POST">
							{% csrf_token %}
							<select name='day' id='id_day'>
								<option value="Monday">Monday</option>
								<option value="Tuesday">Tuesday</option>
								<option value="Wednesday">Wednesday</option>
								<option value="Thursday">Thursday</option>
								<option value="Friday">Friday</option>
								<option value="Saturday">Saturday</option>
								<option value="Sunday">Sunday</option>
							</select>
							<div class="form-group">
                				<div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                    				<input type="text" name="time" id="id_time" class="form-control datetimepicker-input" data-target="#datetimepicker2"/>
                    				<span class="input-group-addon" data-target="#datetimepicker2" data-toggle="datetimepicker">
                        			<span class="fa fa-clock-o"></span>
                    				</span>
				                </div>
				            </div>
							<input class='btn btn-primary' type="submit" value="Submit" />
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endcomment %}
		<div class="col-lg-4">
			<div class='card text-center'>
				<div class="card-header" data-toggle="collapse" href="#form_alert_now"><h4 class='card-title'>Send Alert Now</h4></div>
				<div class='card-block collapse' id="form_alert_now">
					<p>Send a custom text alert right when you click the button</p>
					<p><a class='btn btn-primary' href="{% url 'alert_now' slug=chore.slug %}">Send Alert Now</a></p>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class='card text-center'>
				<div class="card-header" data-toggle="collapse" href="#form_alert_later"><h4 class='card-title'>Send Alert Later</h4></div>
				<div class='card-block collapse' id="form_alert_later">
					<form id="alert_later" action="{% url 'alert_later' slug=chore.slug %}" method="POST">
						{% csrf_token %}
						<div class="form-group">
			                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
			                    <input name='date' id="id_date" type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
			                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
			                    <span class="fa fa-calendar"></span>
			                    </span>
			                </div>
			            </div>
			            <input class='btn btn-primary' type="submit" value="Submit" />
					</form>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class='card text-center'>
				<div class="card-header" data-toggle="collapse" href="#form_alert_recurring"><h4 class='card-title'>Set Recurring Alert</h4></div>
				<div class='card-body collapse' id="form_alert_recurring">
					<form id='alert_recurring' action="{% url 'alert_recurring' slug=chore.slug %}" method="POST">
						{% csrf_token %}
						<select name='day' id='id_day'>
							<option value="Monday">Monday</option>
							<option value="Tuesday">Tuesday</option>
							<option value="Wednesday">Wednesday</option>
							<option value="Thursday">Thursday</option>
							<option value="Friday">Friday</option>
							<option value="Saturday">Saturday</option>
							<option value="Sunday">Sunday</option>
						</select>
						<div class="form-group">
            				<div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                				<input type="text" name="time" id="id_time" class="form-control datetimepicker-input" data-target="#datetimepicker2"/>
                				<span class="input-group-addon" data-target="#datetimepicker2" data-toggle="datetimepicker">
                    			<span class="fa fa-clock-o"></span>
                				</span>
			                </div>
			            </div>
						<input class='btn btn-primary' type="submit" value="Submit" />
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class='row'>
		<div class="col-lg-12">
			<div class="card">
				<h4 class="card-title">Chore Information</h4>
				<div class="card-block">
					<div clas="row"
					<span class="fa fa-info-circle"></span> 
					
				</div>
			</div>
		</div>
	</div>
{% endblock %}

reminder/templates/reminder/view_roommate.html
{% extends 'reminder/base.html' %}
{% block title %} {{ roommate.name }} {% endblock %}

{% block content %}
	<h2>Team: <a href="{{ roommate.team.get_absolute_url }}">{{ roommate.team }}</a></h2>
	<p>Phone Number: {{ roommate.phone_number }}</p>
	<p>Chores:</p>
	<ul>
	{% for chore in roommate.chores.all %}
		<li><a href="{{ chore.get_absolute_url }}">{{ chore.name }}</a></li>
	{% empty %}
		<p>No registered chores for me!</p>
	{% endfor %}
	</ul>
{% endblock %}

reminder/templates/reminder/view_team.html
{% extends 'reminder/base.html' %}
{% block title %} {{ team.name }} {% endblock %}
{% block content %}
	<a href="{% url 'create_roommate' slug=team.slug %}"><i class="fa fa-pencil-square-o"></i> <strong>Add</strong></a>

	<div id="accordionOne" role="tablist">
		<div class="card">
			<div class="card-header" role="tab" id="headingOne" data-toggle="collapse" href="#collapseOne">
				<h5>Roommates</h5>
			</div>
			<div id="collapseOne" class="collapse" role="tabpanel" data-parent="#accordionOne">
				<div class="card-body">
					{% for roommate in team.roommates.all %}
						<li><a href="{{ roommate.get_absolute_url }}">{{ roommate.name }}</a></li>
					{% empty %}
						<p>No roommates registered yet!</p>
						<a href="{% url 'create_roommate' slug=team.slug %}">Add Roommate</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>

	<a href="{% url 'create_chore' slug=team.slug %}"><i class="fa fa-pencil-square-o"></i> <strong>Add</strong></a>
	<div id="accordionTwo" role="tablist">
		<div class="card">
			<div class="card-header" role="tab" id="headingTwo" data-toggle="collapse" href="#collapseTwo">
				<h5>Chores</h5>
			</div>
			<div id="collapseTwo" class="collapse" role="tabpanel" data-parent="#accordionTwo">
				<div class="card-body">
					{% for chore in team.chores.all %}
						<li><a href="{{ chore.get_absolute_url }}">{{ chore.name }}</a></li>
					{% empty %}
						<p>No chores registered yet!</p>
						<a href="{% url 'create_chore' slug=team.slug %}">Add Chore</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}